name = "ianeo-orchestrator"
main = "src/index.ts"
compatibility_date = "2026-08-20"
workers_dev = true
keep_vars = true

[vars]
FAQ_SERVICE_URL = "https://faq.drthorne.uk"

[observability.logs]
enabled = true
head_sampling_rate = 1
